### ISSUE TITLE
Can't launch debugger for Rails project with Rbenv.

### ISSUE THREAD

**Issue by dmitry-goncharuk** [ruby/vscode-rdbg#21]
I'm running Rails project:
- Rails 6.1.4
- Ruby 3.0.3
with Ruby version managed by Rbenv.
I have `gem 'debug'` listed in my project's Gemfile, and binstubs generated to `./bin/rdbg`.
Gems are bundled with Bundler `2.2.32`

Here is the "launch" config I'm trying to use 
```
{
  "name": "Debug Rails server",
  "type": "rdbg",
  "request": "launch",
  "useBundler": false,
  "script": "server",
  "rdbgPath": "${workspaceFolder}/bin/rdbg",
  "command": "${workspaceFolder}/bin/rails",
  "cwd":"${workspaceFolder}"
}
```

I've changed `command` from default to `"${workspaceFolder}/bin/rails"` to bypass logic, described [here](https://github.com/ruby/vscode-rdbg/blob/master/src/extension.ts#L363).
I'm using `zsh` as my shell.
So the problem I've  faced is that function `get_sock_path` generates the next command to shell: `"/bin/zsh -l -c '${workspaceFolder}/bin/rdbg --util=gen-sockpath'"` (`${workspaceFolder}` here and further the absolute path to my project) . And this command, when executed, does not follow `rbenv`'s  shims and thows the error 
```
Activating bundler (2.2.32) failed:
Could not find 'bundler' (2.2.32) required by your ${workspaceFolder}/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.32`
```
This is because `make_shell_command` returns a command (`/bin/zsh -l -c '...'`) that is when executing is not caught by `rbenv` Even If I add `cd ${workspaceFolder}` it won't work:
```
$ /bin/zsh -l -c 'cd ${workspaceFolder} && which ruby'
/usr/bin/ruby
$ /bin/zsh -l -c 'cd ${workspaceFolder} && ruby --version'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
$ git clone git@github.com:ruby/vscode-rdbg.git
$ /bin/zsh -l -c 'cd ${workspaceFolder} && which ruby'
/usr/bin/ruby
$ /bin/zsh -l -c 'cd ${workspaceFolder} && ruby --version'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]


$ cd ${workspaceFolder} && which ruby
$HOME/.rbenv/shims/ruby
$ cd ${workspaceFolder} && ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]
```

I haven't had a chance to debug the extension deeply enough and do not clear to me why is this necessary to use that "sequence", but this causes problems.
Is there any way for code to be changed in order to work properly with such widely used Ruby environment management as `rbenv`?

**Comment by sly7-7** [comment]
Not sure, but I think I have the same kind of problem with rvm. I ended launching my rails app through rdbg from the terminal, and use the `attach` from vscode. The command is something like: `rdbg --open --command --stop-at-load -- bin/rails s` (from the project root directory)

**Comment by dmitry-goncharuk** [comment]
I've managed to "bypass" that with populating $PATH variable when starting new terminal:
```
 {
      "name": "Debug Rails server",
      "type": "rdbg",
      "request": "launch",
      "useBundler": false,
      "script": "server",
      "rdbgPath": "PATH=$HOME/.rbenv/shims:${PATH} ${workspaceFolder}/bin/rdbg",
      "command": "${workspaceFolder}/bin/rails",
      "cwd":"${workspaceFolder}",
 }
```

**Comment by dmitry-goncharuk** [comment]
Not sure why does this happens. But it seems like `PATH` is not populated with `rbenv`'s paths.

I don't use `.zrofile` but `.profile` instead and it, indeed, includes
```
PATH=$PATH:$HOME/.rbenv/shims
```

**Comment by ko1** [comment]
I'll try later (but not high priority). I expect zsh experts solve this issuee ... :p

**Comment by travisp** [comment]
I'm having a similar issue on macos with zsh and chruby even when starting vscode from the terminal, the only way I get rdbg attach to work is to re-order PATH by setting the rdbgPath as follows:
```
"rdbgPath": "PATH=${env:RUBY_ROOT}/bin:${PATH} ${env:GEM_HOME}/bin/rdbg"
```
Otherwise it seems to use the system ruby, despite awareness of the environment variables injected by chruby, apparently because PATH has the following at the start compared to terminal: `/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`. Path is correct in the integrated terminal.

At least in my case this doesn't strike me as a vscode-rdbg issue, even though I haven't had issues with anything else yet, but maybe setting the PATH as I and the previous commenter did will be helpful.

**Comment by vinistock** [comment]
We have the same issue in the Ruby LSP. Version managers, such as `chruby`, will change the order of entries in the `PATH` so that the system Ruby defined in `/usr/bin` doesn't get picked up by accident when running a binstub.

In the Ruby LSP, we're exposing a configuration to let users select their version manager and then we use to activate the environment before running commands ([here](https://github.com/Shopify/vscode-ruby-lsp/blob/5a6793e35b7110676817c00fe26782cd14783d47/src/ruby.ts#L25)). How do you feel about bringing similar logic to activate environments to rdbg?

In addition to fixing this specific issue, it also guarantees that switching between projects that use different Ruby versions will have their environments re-activated.
